version: '3'

networks: 
   laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_laravel
        ports:
            - "7000:80" 
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks:
            - laravel
        
    mysql:
        image: mysql
        container_name: mysql_laravel
        restart: unless-stopped
        tty: true
        ports:
          - "9306:3306"
        environment:
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel_db
          MYSQL_PASSWORD: 1234567
          MYSQL_ROOT_PASSWORD: 1234567
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        networks:
            - laravel
        volumes:
          - ./mysql:/var/lib/mysql
       
    php:
       build:
         context: .
         dockerfile: Dockerfile
       container_name: php_laravel
       volumes:
         - ./src:/var/www/html
       ports:
         - "9004"
       networks:
         - laravel
