version: '3'
services:
    # NGINX build
    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: isaacalves7/nginx
        container_name: nginx_laravel
        ports:
            - "7000:80"
        volumes:
         - ./src:/var/www/html
         - ./src:/
        networks: 
            - production-network
        depends_on: 
            - "app.laravel1"
            - "app.laravel2"
            - "app.laravel3"
        
    # MySQL build 
    mysql:
        image: mysql
        networks: 
            - production-network

    # Laravel App 1
    laravel1:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: isaacalves7/app-laravel
        container_name: app.laravel1
        ports:
            - "3000"
        networks: 
            - production-network
        depends_on:
            - "mysql"

    # Laravel App 2
    laravel2:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: isaacalves7/app-laravel
        container_name: app.laravel2
        ports:
            - "3000"
        networks: 
            - production-network
        depends_on:
            - "mysql"

    # Laravel App 3
    laravel3:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: isaacalves7/app-laravel
        container_name: app.laravel3
        ports:
            - "3000"
        networks: 
            - production-network
        depends_on:
            - "mysql"

# Networks
networks: 
    production-network:
        driver: bridge
